# -*- coding: utf-8 -*-
"""Фото-текст бот .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRUeqRHlp6dzwpEq7ZfX3ngQw2BgE4bJ
"""

!pip install telebot

!pip install aspose-words



import easyocr
import telebot
from telebot import types
import requests

def ocr(file):
  reader = easyocr.Reader(['ru'])
  result = reader.readtext(file, detail = 0)
  spis =' '.join(result)
  return spis

def document (file):
    with open("file.txt", "w") as output:
      output.write(file)
    return output



from os import close
bot = telebot.TeleBot('7597231529:AAEeOwH4slLgRjOI5PCl_6XxtLSy2z7ARw8')
@bot.message_handler(commands=['start'])
def hello(message):
  bot.send_message(message.chat.id, 'Здравствуйте, отправьте ваше фото')

@bot.message_handler(content_types=['photo'])
def handle_docs_document(message):
        file_info = bot.get_file(message.photo[len(message.photo) - 1].file_id)
        downloaded_file = bot.download_file(file_info.file_path)
        new_file = ocr(downloaded_file)
        file = open('file.doc', 'w')
        file.write(new_file)
        file.close()
        file = open('file.doc', 'r')

        bot.send_document(message.chat.id, file)
        bot.send_message(message.chat.id, 'Файл готов')
        file.close()



bot.infinity_polling()

